CREATE TABLE IF NOT EXISTS users(
userID   TEXT,
email    VARCHAR(40) UNIQUE NOT NULL,
hash     TEXT UNIQUE NOT NULL,
name     VARCHAR(35),
validated boolean default (false),
primary key (email)
);

CREATE TABLE IF NOT EXISTS  students(
email varchar(40) not null,
name varchar(35) not null,
GPA decimal(3,2) ,
FOREIGN KEY (email) REFERENCES users(email) on delete cascade on update cascade,
primary key (email)
);

CREATE TABLE IF NOT EXISTS  departments(
Name varchar(30),
primary key (name)
);

CREATE TABLE IF NOT EXISTS  courses(
CRN Varchar(10),
Name varchar(30),
credits integer,    
primary key (CRN)
);

CREATE TABLE IF NOT EXISTS  MajorsIn(
email varchar(40) not null,
name varchar(30) not null,
FOREIGN KEY (email) REFERENCES students (email) on delete cascade on update cascade,
FOREIGN KEY (name) REFERENCES departments (name) on delete cascade on update cascade,
PRIMARY KEY (email,name)
);

CREATE TABLE  IF NOT EXISTS departmentCourses(
CRN Varchar(10),
Name varchar(30),
FOREIGN KEY (CRN) REFERENCES Courses (CRN) on delete cascade on update cascade,
FOREIGN KEY (Name) REFERENCES Departments (Name) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS Semesters(
semesterID varchar(30),
primary key (semesterID)
);

CREATE TABLE IF NOT EXISTS  TakenCourses(
semesterID varchar(30),
email varchar(40) not null,
name varchar(30) not null,
FOREIGN KEY (email) REFERENCES students (email) on delete cascade on update cascade,
FOREIGN KEY (name) REFERENCES departments (name) on delete cascade on update cascade,
FOREIGN KEY (semesterID) REFERENCES Semesters(semesterID) on delete cascade on update cascade,
PRIMARY KEY (SemesterId,email,name)
);


-- Insert into deparments
INSERT INTO Departments VALUES ('ACCOUNTING');
INSERT INTO Departments VALUES ('ADULT EDUCATION');
INSERT INTO Departments VALUES ('AGRI SYSTEMS TECHNOLOGIES');
INSERT INTO Departments VALUES ('AGRICULTURAL ECONOMICS');
INSERT INTO Departments VALUES ('AGRICULTURE');
INSERT INTO Departments VALUES ('AGRICULTURE EDUCATION');
INSERT INTO Departments VALUES ('ANIMAL SCIENCE');
INSERT INTO Departments VALUES ('ANTHROPOLOGY');
INSERT INTO Departments VALUES ('ART');
INSERT INTO Departments VALUES ('ART EDUCATION');
INSERT INTO Departments VALUES ('ART HISTORY');
INSERT INTO Departments VALUES ('ATHLETIC TRAINING');
INSERT INTO Departments VALUES ('BIOLOGY');
INSERT INTO Departments VALUES ('BIOLOGY - GENERAL EDUCATION');
INSERT INTO Departments VALUES ('BUSINESS');
INSERT INTO Departments VALUES ('BUSINESS ADMINISTRATION');
INSERT INTO Departments VALUES ('BUSINESS COMMUNICATION');
INSERT INTO Departments VALUES ('BUSINESS EDUCATION');
INSERT INTO Departments VALUES ('BUSINESS SYSTEMS');
INSERT INTO Departments VALUES ('BUSINESS TECHNOLOGY');
INSERT INTO Departments VALUES ('CHEMISTRY');
INSERT INTO Departments VALUES ('CIVIL ENGINEERING');
INSERT INTO Departments VALUES ('CLINICAL LABORATORY SCIENCES');
INSERT INTO Departments VALUES ('COLLEGE STUDENT PERSONNEL SERV');
INSERT INTO Departments VALUES ('COMMUNICATION DISORDERS');
INSERT INTO Departments VALUES ('COMMUNICATION STUDIES');
INSERT INTO Departments VALUES ('COMMUNITY COLLEGE EDUCATION');
INSERT INTO Departments VALUES ('COMPUTER AND INFORMATION TECH');
INSERT INTO Departments VALUES ('COMPUTER SCIENCE');
INSERT INTO Departments VALUES ('COMPUTER SCIENCE EDUCATION');
INSERT INTO Departments VALUES ('COUNSELING');
INSERT INTO Departments VALUES ('CRIMINOLOGY');
INSERT INTO Departments VALUES ('DATA SCIENCE AND ANALYTICS');
INSERT INTO Departments VALUES ('DELTA CENTER FOR ECONOMIC DEV');
INSERT INTO Departments VALUES ('DIGITAL DESIGN LANGUAGE');
INSERT INTO Departments VALUES ('DISASTER LIFE SUPPORT');
INSERT INTO Departments VALUES ('DISASTER PREP & EMERGENCY MGMT');
INSERT INTO Departments VALUES ('EARLY CHILDHOOD');
INSERT INTO Departments VALUES ('ECONOMICS');
INSERT INTO Departments VALUES ('EDUCATION');
INSERT INTO Departments VALUES ('EDUCATIONAL LEADERSHIP ADMIN');
INSERT INTO Departments VALUES ('EDUCATIONAL LEADERSHIP CURRICU');
INSERT INTO Departments VALUES ('EDUCATIONAL LEADERSHIP FOUNDAT');
INSERT INTO Departments VALUES ('EDUCATIONAL LEADERSHIP SPECIAL');
INSERT INTO Departments VALUES ('ELECTRICAL ENGINEERING');
INSERT INTO Departments VALUES ('ELEMENTARY EDUCATION');
INSERT INTO Departments VALUES ('EMERGENCY MED SERV PARAMEDIC');
INSERT INTO Departments VALUES ('EMERGENCY MEDICAL SERVICES');
INSERT INTO Departments VALUES ('ENGINEERING');
INSERT INTO Departments VALUES ('ENGINEERING MANAGEMENT');
INSERT INTO Departments VALUES ('ENGLISH');
INSERT INTO Departments VALUES ('ENVIRONMENTAL SCIENCES');
INSERT INTO Departments VALUES ('EXERCISE SCIENCE');
INSERT INTO Departments VALUES ('EXERCISE SCIENCE-PHYSICAL ED');
INSERT INTO Departments VALUES ('FINANCE');
INSERT INTO Departments VALUES ('FOOD SCIENCE TECHNOLOGY');
INSERT INTO Departments VALUES ('FRENCH');
INSERT INTO Departments VALUES ('GEOGRAPHY');
INSERT INTO Departments VALUES ('GEOLOGY');
INSERT INTO Departments VALUES ('GERMAN');
INSERT INTO Departments VALUES ('GLOBAL SUPPLY CHAIN MANAGEMENT');
INSERT INTO Departments VALUES ('GRAPHIC COMMUNICATIONS');
INSERT INTO Departments VALUES ('GRAPHIC DESIGN');
INSERT INTO Departments VALUES ('HEALTH');
INSERT INTO Departments VALUES ('HEALTH CARE ADMINISTRATION');
INSERT INTO Departments VALUES ('HEALTH PE EXERCISE SCIENCE');
INSERT INTO Departments VALUES ('HEALTH PROFESSIONS');
INSERT INTO Departments VALUES ('HERITAGE STUDIES');
INSERT INTO Departments VALUES ('HISTORY');
INSERT INTO Departments VALUES ('HOMELAND SECURITY');
INSERT INTO Departments VALUES ('HONORS');
INSERT INTO Departments VALUES ('HORTICULTURE');
INSERT INTO Departments VALUES ('HOSPITALITY MANAGEMENT');
INSERT INTO Departments VALUES ('HOWL TRANSITION PROGRAM');
INSERT INTO Departments VALUES ('INFO SYS & BUSINESS ANALYTICS');
INSERT INTO Departments VALUES ('INTENSIVE ENGLISH');
INSERT INTO Departments VALUES ('INTERDISCIPLINARY STUDIES');
INSERT INTO Departments VALUES ('INTERNATIONAL BUSINESS');
INSERT INTO Departments VALUES ('INTERNATIONAL BUSINESS STUDIES');
INSERT INTO Departments VALUES ('INTERNATIONAL PROGRAMS');
INSERT INTO Departments VALUES ('INTERNATIONAL STUDIES');
INSERT INTO Departments VALUES ('JOURNALISM');
INSERT INTO Departments VALUES ('LAW');
INSERT INTO Departments VALUES ('LIBRARY');
INSERT INTO Departments VALUES ('MAGNETIC RESONANCE IMAGING');
INSERT INTO Departments VALUES ('MANAGEMENT');
INSERT INTO Departments VALUES ('MANAGEMENT INFORMATION SYSTEMS');
INSERT INTO Departments VALUES ('MARKETING');
INSERT INTO Departments VALUES ('MASS COMMUNICATIONS');
INSERT INTO Departments VALUES ('MASTER OF BUSINESS ADMINISTRAT');
INSERT INTO Departments VALUES ('MATHEMATICS');
INSERT INTO Departments VALUES ('MECHANICAL ENGINEERING');
INSERT INTO Departments VALUES ('MEDIAMEDIA AND COMMUNICATION');
INSERT INTO Departments VALUES ('METHOD AND MAT FOR LANGUAGES');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH AGRI EDU');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH BUED VOC');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH ENGLISH');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH MATH');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH PHYS ED');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH SCIENCE');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH SCOM THEA');
INSERT INTO Departments VALUES ('METHOD AND MAT TEACH SOCIAL ST');
INSERT INTO Departments VALUES ('METHOD AND MATERIALS TEACH ART');
INSERT INTO Departments VALUES ('MID LEVEL EDUCATION');
INSERT INTO Departments VALUES ('MILITARY SCIENCE AND LEADER');
INSERT INTO Departments VALUES ('MOLECULAR BIOSCIENCE');
INSERT INTO Departments VALUES ('MUSEUM STUDIES');
INSERT INTO Departments VALUES ('MUSIC');
INSERT INTO Departments VALUES ('MUSIC EDUCATION');
INSERT INTO Departments VALUES ('MUSIC PERFORMANCE');
INSERT INTO Departments VALUES ('NUCLEAR MEDICINE');
INSERT INTO Departments VALUES ('NURSING');
INSERT INTO Departments VALUES ('NURSING - GRADUATE');
INSERT INTO Departments VALUES ('NURSING PRACTICUM');
INSERT INTO Departments VALUES ('NUTRITIONAL SCIENCE');
INSERT INTO Departments VALUES ('NUTRITIONAL SCIENCE PRACTICUM');
INSERT INTO Departments VALUES ('OCCUPATIONAL ENV SAFETY & HLTH');
INSERT INTO Departments VALUES ('OCCUPATIONAL THERAPY ASSISTANT');
INSERT INTO Departments VALUES ('OCCUPATIONAL THERAPY DOCTORATE');
INSERT INTO Departments VALUES ('PHILOSOPHY');
INSERT INTO Departments VALUES ('PHYSICAL EDUCATION');
INSERT INTO Departments VALUES ('PHYSICAL SCIENCE');
INSERT INTO Departments VALUES ('PHYSICAL SCIENCE GENERAL');
INSERT INTO Departments VALUES ('PHYSICAL THERAPIST ASSISTANT');
INSERT INTO Departments VALUES ('PHYSICAL THERAPY');
INSERT INTO Departments VALUES ('PHYSICS');
INSERT INTO Departments VALUES ('PLANT AND SOIL SCIENCE');
INSERT INTO Departments VALUES ('POLITICAL SCIENCE');
INSERT INTO Departments VALUES ('PSYCHOLOGY');
INSERT INTO Departments VALUES ('RADIATION THERAPY');
INSERT INTO Departments VALUES ('RADIO TELEVISION');
INSERT INTO Departments VALUES ('RADIOGRAPHY');
INSERT INTO Departments VALUES ('RADIOLOGIC SCIENCE');
INSERT INTO Departments VALUES ('RADIOLOGIC SCIENCES LIMIT TECH');
INSERT INTO Departments VALUES ('RADIOLOGIC TECHNOLOGY');
INSERT INTO Departments VALUES ('READING');
INSERT INTO Departments VALUES ('REAL ESTATE AND INSURANCE');
INSERT INTO Departments VALUES ('RELIGION');
INSERT INTO Departments VALUES ('RENEWABLE ENERGY TECHNOLOGY');
INSERT INTO Departments VALUES ('SECONDARY EDUCATION');
INSERT INTO Departments VALUES ('SOCIAL WORK');
INSERT INTO Departments VALUES ('SOCIOLOGY');
INSERT INTO Departments VALUES ('SPANISH');
INSERT INTO Departments VALUES ('STATISTICS');
INSERT INTO Departments VALUES ('STRATEGIC COMMUNICATION');
INSERT INTO Departments VALUES ('SURVEYING');
INSERT INTO Departments VALUES ('TEACHER EDUCATION');
INSERT INTO Departments VALUES ('TEACHING INTERNSHIP SECONDARY');
INSERT INTO Departments VALUES ('TECHNOLOGY');
INSERT INTO Departments VALUES ('THEATRE ARTS');
INSERT INTO Departments VALUES ('ULTRASOUND');
INSERT INTO Departments VALUES ('UNIVERSITY COLLEGE');
INSERT INTO Departments VALUES ('VOCATIONAL EDUCATION');
INSERT INTO Departments VALUES ('WOMEN AND GENDER STUDIES');
INSERT INTO Departments VALUES ('WORLD LANGUAGES');
INSERT INTO Departments VALUES ('ZOOLOGY');
-- Semester
INSERT INTO Semesters VALUES ('FALL 2022');
