CREATE TABLE IF NOT EXISTS users(
userID   TEXT,
email    VARCHAR(40) not null,
hash     TEXT UNIQUE NOT NULL,
name     VARCHAR(35),
validated boolean default (false),
primary key (userID)
);

CREATE TABLE IF NOT EXISTS  students(
email varchar(40) not null,
name varchar(35) not null,
GPA decimal(3,2) ,
FOREIGN KEY (email) REFERENCES users(email) on delete cascade on update cascade,
primary key (email)
);

CREATE TABLE IF NOT EXISTS  departments(
Name varchar(30),
primary key (name)
);

CREATE TABLE IF NOT EXISTS  courses(
CRN Varchar(10),
Name varchar(30),
credits integer,    
primary key (CRN)
);

CREATE TABLE IF NOT EXISTS  MajorsIn(
email varchar(40) not null,
name varchar(30) not null,
FOREIGN KEY (email) REFERENCES students (email) on delete cascade on update cascade,
FOREIGN KEY (name) REFERENCES departments (name) on delete cascade on update cascade,
PRIMARY KEY (email,name)
);

CREATE TABLE  IF NOT EXISTS departmentCourses(
CRN Varchar(10),
Name varchar(30),
FOREIGN KEY (CRN) REFERENCES Courses (CRN) on delete cascade on update cascade,
FOREIGN KEY (Name) REFERENCES Departments (Name) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS Semesters(
semesterID varchar(30),
primary key (semesterID)
);

CREATE TABLE IF NOT EXISTS  TakenCourses(
semesterID varchar(30),
email varchar(40) not null,
name varchar(30) not null,
FOREIGN KEY (email) REFERENCES students (email) on delete cascade on update cascade,
FOREIGN KEY (name) REFERENCES departments (name) on delete cascade on update cascade,
FOREIGN KEY (semesterID) REFERENCES Semesters(semesterID) on delete cascade on update cascade,
PRIMARY KEY (SemesterId,email,name)
);


-- Insert into deparments
INSERT INTO Departments VALUES ('ACCOUNTING');
INSERT INTO Departments VALUES ('ADDICTION STUDIES');
INSERT INTO Departments VALUES ('ADULT-GERONTOLOGY');
INSERT INTO Departments VALUES ('AFRICAN AMERICAN STUDIES');
INSERT INTO Departments VALUES ('AGRICULTURAL BUSINESS');
INSERT INTO Departments VALUES ('AGRICULTURAL MECHANICS');
INSERT INTO Departments VALUES ('AGRICULTURAL STUDIES');
INSERT INTO Departments VALUES ('AGRICULTURE');
INSERT INTO Departments VALUES ('ANDROID APPLICATION DEVELOPMENT');
INSERT INTO Departments VALUES ('ANIMAL SCIENCE');
INSERT INTO Departments VALUES ('APPLIED SCIENCE');
INSERT INTO Departments VALUES ('ART');
INSERT INTO Departments VALUES ('ART HISTORY');
INSERT INTO Departments VALUES ('ATHLETIC TRAINING');
INSERT INTO Departments VALUES ('BIOLOGICAL SCIENCES');
INSERT INTO Departments VALUES ('BIOTECHNOLOGY');
INSERT INTO Departments VALUES ('BONE DENSITOMETRY');
INSERT INTO Departments VALUES ('BUILDING-LEVEL/PRINCIPAL');
INSERT INTO Departments VALUES ('BUSINESS ADMINISTRATION');
INSERT INTO Departments VALUES ('BUSINESS ANALYTICS');
INSERT INTO Departments VALUES ('BUSINESS ECONOMICS');
INSERT INTO Departments VALUES ('BUSINESS LAW AND COMPLIANCE');
INSERT INTO Departments VALUES ('BUSINESS TECHNOLOGY');
INSERT INTO Departments VALUES ('CHEMISTRY');
INSERT INTO Departments VALUES ('CHILDREN''S ADVOCACY STUDIES');
INSERT INTO Departments VALUES ('CIVIL ENGINEERING');
INSERT INTO Departments VALUES ('CLINICAL LABORATORY SCIENCE');
INSERT INTO Departments VALUES ('COLLEGE STUDENT PERSONNEL SERVICES');
INSERT INTO Departments VALUES ('COMMUNICATION DISORDERS');
INSERT INTO Departments VALUES ('COMMUNICATION STUDIES');
INSERT INTO Departments VALUES ('COMPUTED TOMOGRAPHY');
INSERT INTO Departments VALUES ('COMPUTER AND INFORMATION TECHNOLOGY');
INSERT INTO Departments VALUES ('COMPUTER SCIENCE');
INSERT INTO Departments VALUES ('CORPORATE MEDIA');
INSERT INTO Departments VALUES ('CREATIVE MEDIA PRODUCTION');
INSERT INTO Departments VALUES ('CRIMINAL JUSTICE');
INSERT INTO Departments VALUES ('CRIMINOLOGY');
INSERT INTO Departments VALUES ('CROP CONSULTING AND AGRONOMIC SERVICES');
INSERT INTO Departments VALUES ('CURRICULUM AND INSTRUCTION');
INSERT INTO Departments VALUES ('CYBER SECURITY');
INSERT INTO Departments VALUES ('DATA ANALYTICS');
INSERT INTO Departments VALUES ('DATA SCIENCE');
INSERT INTO Departments VALUES ('DATA SCIENCE AND DATA ANALYTICS');
INSERT INTO Departments VALUES ('DEBATE AND FORENSICS');
INSERT INTO Departments VALUES ('DIETETICS');
INSERT INTO Departments VALUES ('DIGITAL DESIGN');
INSERT INTO Departments VALUES ('DIGITAL TECHNOLOGY & DESIGN');
INSERT INTO Departments VALUES ('DISASTER PREPAREDNESS');
INSERT INTO Departments VALUES ('DYSLEXIA ENDORSEMENT');
INSERT INTO Departments VALUES ('EARLY CHILDHOOD EDUCATION');
INSERT INTO Departments VALUES ('EARLY CHILDHOOD SERVICES');
INSERT INTO Departments VALUES ('ECONOMICS');
INSERT INTO Departments VALUES ('EDUCATIONAL LEADERSHIP');
INSERT INTO Departments VALUES ('ELECTRICAL ENGINEERING');
INSERT INTO Departments VALUES ('ELECTRONIC COMMERCE');
INSERT INTO Departments VALUES ('ELEMENTARY EDUCATION');
INSERT INTO Departments VALUES ('EMERGENCY MEDICAL TECHNICIAN');
INSERT INTO Departments VALUES ('ENGINEERING');
INSERT INTO Departments VALUES ('ENGINEERING MANAGEMENT');
INSERT INTO Departments VALUES ('ENGINEERING MANAGEMENT SYSTEMS');
INSERT INTO Departments VALUES ('ENGINEERING TECHNOLOGY');
INSERT INTO Departments VALUES ('ENGLISH');
INSERT INTO Departments VALUES ('ENGLISH AS A SECOND LANGUAGE');
INSERT INTO Departments VALUES ('ENTREPRENEURSHIP');
INSERT INTO Departments VALUES ('ENVIRONMENTAL SCIENCE');
INSERT INTO Departments VALUES ('ENVIRONMENTAL SCIENCES');
INSERT INTO Departments VALUES ('ENVIRONMENTAL STUDIES');
INSERT INTO Departments VALUES ('EXERCISE SCIENCE');
INSERT INTO Departments VALUES ('FAMILY NURSE PRACTITIONER');
INSERT INTO Departments VALUES ('FINANCE');
INSERT INTO Departments VALUES ('FINANCIAL WEALTH MANAGEMENT');
INSERT INTO Departments VALUES ('FOLKLORE STUDIES');
INSERT INTO Departments VALUES ('FRENCH');
INSERT INTO Departments VALUES ('GENERAL BUSINESS');
INSERT INTO Departments VALUES ('GENERAL SCIENCES');
INSERT INTO Departments VALUES ('GENERAL STUDIES');
INSERT INTO Departments VALUES ('GERMAN');
INSERT INTO Departments VALUES ('GLOBAL SUPPLY CHAIN MANAGEMENT');
INSERT INTO Departments VALUES ('GRAPHIC COMMUNICATION');
INSERT INTO Departments VALUES ('GRAPHIC DESIGN');
INSERT INTO Departments VALUES ('HEALTH COMMUNICATIONS');
INSERT INTO Departments VALUES ('HEALTH PROMOTION');
INSERT INTO Departments VALUES ('HEALTH STUDIES');
INSERT INTO Departments VALUES ('HERITAGE STUDIES');
INSERT INTO Departments VALUES ('HIGH PERFORMANCE COMPUTING');
INSERT INTO Departments VALUES ('HISTORY');
INSERT INTO Departments VALUES ('HORTICULTURE');
INSERT INTO Departments VALUES ('HOSPITALITY AND EVENT TOURISM MANAGEMENT	');
INSERT INTO Departments VALUES ('INFORMATION TECHNOLOGY');
INSERT INTO Departments VALUES ('INSTRUCTIONAL TECHNOLOGY SPECIALIST');
INSERT INTO Departments VALUES ('INTERDISCIPLINARY FAMILY STUDIES');
INSERT INTO Departments VALUES ('INTERDISCIPLINARY STUDIES');
INSERT INTO Departments VALUES ('INTERNATIONAL BUSINESS');
INSERT INTO Departments VALUES ('INTERNATIONAL STUDIES');
INSERT INTO Departments VALUES ('LEADERSHIP STUDIES');
INSERT INTO Departments VALUES ('LOGISTICS');
INSERT INTO Departments VALUES ('MANAGEMENT');
INSERT INTO Departments VALUES ('MARINE SCIENCE');
INSERT INTO Departments VALUES ('MARKETING');
INSERT INTO Departments VALUES ('MATHEMATICS');
INSERT INTO Departments VALUES ('MECHANICAL ENGINEERING');
INSERT INTO Departments VALUES ('MEDIA MANAGEMENT');
INSERT INTO Departments VALUES ('MEDIEVAL STUDIES');
INSERT INTO Departments VALUES ('MENTAL HEALTH COUNSELING');
INSERT INTO Departments VALUES ('MILITARY SCIENCE AND LEADERSHIP');
INSERT INTO Departments VALUES ('MODERN EUROPEAN STUDIES');
INSERT INTO Departments VALUES ('MOLECULAR BIOSCIENCES');
INSERT INTO Departments VALUES ('MULTIMEDIA JOURNALISM');
INSERT INTO Departments VALUES ('MUSIC');
INSERT INTO Departments VALUES ('MUSIC EDUCATION');
INSERT INTO Departments VALUES ('NURSE ADMINISTRATION');
INSERT INTO Departments VALUES ('NURSE EDUCATOR');
INSERT INTO Departments VALUES ('NURSING');
INSERT INTO Departments VALUES ('OCCUPATIONAL ENVIRONMENTAL SAFETY AND HEALTH');
INSERT INTO Departments VALUES ('ORGANIZATIONAL SUPERVISION');
INSERT INTO Departments VALUES ('PARAMEDIC');
INSERT INTO Departments VALUES ('PHILOSOPHY');
INSERT INTO Departments VALUES ('PHYSICAL EDUCATION');
INSERT INTO Departments VALUES ('PHYSICAL THERAPY');
INSERT INTO Departments VALUES ('PHYSICS');
INSERT INTO Departments VALUES ('PLANT AND SOIL SCIENCE');
INSERT INTO Departments VALUES ('POLITICAL SCIENCE');
INSERT INTO Departments VALUES ('PRECISION AGRICULTURE');
INSERT INTO Departments VALUES ('PSYCHOLOGY');
INSERT INTO Departments VALUES ('RADIOLOGIC SCIENCES');
INSERT INTO Departments VALUES ('RELIGIOUS STUDIES');
INSERT INTO Departments VALUES ('RENEWABLE ENERGY TECHNOLOGY');
INSERT INTO Departments VALUES ('SCHOOL COUNSELING');
INSERT INTO Departments VALUES ('SOCIAL SCIENCE');
INSERT INTO Departments VALUES ('SOCIAL WORK');
INSERT INTO Departments VALUES ('SOCIOLOGY');
INSERT INTO Departments VALUES ('SPANISH');
INSERT INTO Departments VALUES ('SPECIAL EDUCATION');
INSERT INTO Departments VALUES ('SPORT ADMINISTRATION');
INSERT INTO Departments VALUES ('SPORT MANAGEMENT');
INSERT INTO Departments VALUES ('SPORTS PRODUCTION');
INSERT INTO Departments VALUES ('STATISTICS');
INSERT INTO Departments VALUES ('STRATEGIC COMMUNICATION');
INSERT INTO Departments VALUES ('SUPERINTENDENT EDUCATION');
INSERT INTO Departments VALUES ('SWIFT CODING');
INSERT INTO Departments VALUES ('TEACHING');
INSERT INTO Departments VALUES ('THEATRE');
INSERT INTO Departments VALUES ('UNITED STATES HISTORY');
INSERT INTO Departments VALUES ('WILDLIFE, FISHERIES, AND CONSERVATION');
INSERT INTO Departments VALUES ('WOMEN AND GENDER STUDIES');
INSERT INTO Departments VALUES ('WORLD LANGUAGES AND CULTURE');
INSERT INTO Departments VALUES ('WRITING STUDIES');

-- Semester
INSERT INTO Semesters VALUES ('FALL 2022');
